# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-04 16:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_auto_20190304_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ts',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 3, 4, 16, 59, 31, 214793, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
